apiVersion: v1
kind: apiVersion: v1
metadata: 
   name: mynginx
spec:
 replicas: 3
 selector:
   app: mynginx


template:
   metadata: 
     labels: 
        app: mynginx
spec:
   containers:
   - name: mynginx
     image: nginx
     port:
     - containersport: 8080
