apiVersion: v1
kind: ReplicationController
metadata: 
   name: mynginx
spec:
 replicas: 3
 selector:
   app: mynginx
 template:
   metadata: 
     labels: 
        app: mynginx
   spec:
   containers:
   - name: mynginx
     image: nginx
     port:
     - containersport: 80
     containers:
     - name: mynginx
       image: nginx
       ports:
        containersport: 80